name: 'schedule'

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'

jobs:
  gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ttionya/Repository-Sync-Hub@v1
        with:
          target_repository: 'https://gitee.com/ttionya/Personal-VPS-Shell.git'
          http_access_name: 'ttionya'
          http_access_token: ${{ secrets.GITEE_HTTP_ACCESS_TOKEN }}
